Update wtag SF
bu-cms/bucoffea pull request #146
Opened 2020-01-29 22:36 UTC by siqiyyyy

According to update here https://www.dropbox.com/s/z1rnuaxrekmrvlu/DeepAK8_Top_W_SFs_V2_Training_FINAL_w_Tables.pdf?dl=0

2020-01-29 22:38 UTC, siqiyyyy commented
Let me also update the WPs before merging

2020-01-31 00:21 UTC, AndreasAlbert requested changes

2020-01-31 00:21 UTC, AndreasAlbert commented on bucoffea/config/monojet.yaml
> -    monov: False
I know its kind of annoying, but could we switch this back?

2020-01-31 00:21 UTC, AndreasAlbert commented on bucoffea/config/monojet.yaml
> -  wtag: # https://indico.cern.ch/event/840827/contributions/3527925/attachments/1895214/3126510/DeepAK8_Top_W_SFs_2017_JMAR_PK.pdf
For future reference, could you add the slides here?

2020-01-31 00:21 UTC, AndreasAlbert commented on bucoffea/config/monojet.yaml
> -    wtag_loose: # https://indico.cern.ch/event/840827/contributions/3527925/attachments/1895214/3126510/DeepAK8_Top_W_SFs_2017_JMAR_PK.pdf
same

2020-01-31 17:18 UTC, siqiyyyy commented
Added those changes

2020-02-07 18:25 UTC, merged