fix potential full pipe durong file merging with big files
bu-cms/bucoffea pull request #47
Opened 2019-10-24 05:26 UTC by siqiyyyy

Transferring the merged item between the child process and the parent process could potentially block the pipeline. To avoid that, we should instead let the child processes read, merge, and write on its own without transferring any data between processes.

2019-10-24 13:24 UTC, AndreasAlbert commented
Good thinking! I'd be worried whether the writing is thread safe in the implementation here. Could we include a locking mechanism as explained [here](http://effbot.org/zone/thread-synchronization.htm#locks) ?

2019-10-24 13:28 UTC, AndreasAlbert commented
[klepto documentation](https://pypi.org/project/klepto/) is pretty vagues on this. It has this paragraph, which may or may not speak to thread-safe writing:

> klepto provides both standard and “safe” caching, where “safe” caches are slower but can recover from hashing errors. klepto is intended to be used for distributed and parallel computing, where several of the keymaps serialize the stored objects. Caches and archives are intended to be read/write accessible from different threads and processes. klepto enables a user to decorate a function, save the results to a file or database archive, close the interpreter, start a new session, and reload the function and it’s cache.


Let's just lock it ourselves to avoid unforeseen consequences in future runs.

2019-10-24 13:47 UTC, AndreasAlbert commented
also, there is a leftover [archive](https://github.com/bu-cms/bucoffea/pull/47/files#diff-04f3564d64dd8ebe70fb660b74677c99R100-L95) that we don't need anymore, right?

2019-10-24 14:36 UTC, AndreasAlbert requested changes

2019-10-24 14:36 UTC, AndreasAlbert commented on bucoffea/helpers/merging.py
> +    arc.dump()
I think klepto allows us to do `arc.dump(key)` instead.

That does not make a functional difference in this case, since the just-loaded archives will only ever have the key we just wrote into it, as we did not load anything. However, in this way it is clearer to understand what we are trying to do here.

2019-10-24 14:37 UTC, AndreasAlbert commented
I posted a question about this on the [klepto github](https://github.com/uqfoundation/klepto/issues/78), so let's see what they recommend

2019-10-24 14:39 UTC, siqiyyyy commented
> 
> 
> also, there is a leftover [archive](https://github.com/bu-cms/bucoffea/pull/47/files#diff-04f3564d64dd8ebe70fb660b74677c99R100-L95) that we don't need anymore, right?

what leftover archive do you mean?

2019-10-24 14:47 UTC, AndreasAlbert commented
[Click me](https://github.com/bu-cms/bucoffea/pull/47/files#diff-04f3564d64dd8ebe70fb660b74677c99R100-L95)

2019-10-24 14:48 UTC, siqiyyyy commented
oh yes, I'll remove that

2019-10-28 15:24 UTC, siqiyyyy commented on bucoffea/helpers/merging.py
> +    arc.dump()
This is fixed.

2019-10-28 15:26 UTC, AndreasAlbert commented
thanks for the update. I tested this new method by merging a full set of output files with the new and old implementations. The output files of both methods are identical, so I'm going to say this is OK for now.

2019-10-28 15:29 UTC, merged