Add MET trigger plots
bu-cms/bucoffea pull request #82
Opened 2019-11-15 18:58 UTC by alpakpinar

2019-11-15 20:09 UTC, AndreasAlbert requested changes

2019-11-15 20:09 UTC, AndreasAlbert commented on bucoffea/plot/trigger.py
> +    if distribution == 'recoil':
please make this an external option rather than hardcoding

2019-11-20 18:09 UTC, AndreasAlbert commented
This can be merged, right?

2019-11-20 18:26 UTC, alpakpinar commented
Yes, if it looks fine to you, we can merge it.

2019-11-20 18:27 UTC, merged